"""Glosario de traduccion de los casos de uso de IA, en frases sueltas.

Vive aparte de `traducir_casos_ia.py` para que la revision del glosario —que es
donde esta la decision de terminologia y lo unico que un consultor necesita
auditar— no haya que hacerla entre medias de la logica de reescritura del zip.

Se traduce frase a frase y no cadena a cadena a proposito: los casos de uso son
listas separadas por "; " y las frases se repiten mucho entre dominios. Un
glosario de frases es lo que garantiza que el mismo caso de uso se lea igual en
los nueve Excel, y ademas cabe en una revision.

Criterio acordado: se traduce lo que tiene equivalente asentado en espanol y se
dejan intactas solo las siglas del sector (DSO, KYC, RFP, SoW, M&A, P2P/O2C,
10Q/10K, MD&A) y los nombres de producto (FinanceAI Insights Platform,
Digital Analyst, GenAI).
"""

GLOSARIO = {
    # --- IA como sujeto o calificativo ---
    "AI agents for algorithmic trading and market simulation": "Agentes de IA para trading algorítmico y simulación de mercado",
    "AI agents for credit underwriting": "Agentes de IA para el análisis de riesgo crediticio",
    "AI agents for customer success": "Agentes de IA para el éxito del cliente",
    "AI agents for service lifecycle management": "Agentes de IA para la gestión del ciclo de vida del servicio",
    "AI agents for software engineering": "Agentes de IA para ingeniería de software",
    "AI assistant for vehicle buying and leasing": "Asistente de IA para la compra y el leasing de vehículos",
    "AI reconciliation": "Conciliación con IA",
    "AI-driven permitting": "Gestión de permisos basada en IA",
    "AI-driven predictive maintenance": "Mantenimiento predictivo basado en IA",
    "AI-driven visual inspection for particulate matter": "Inspección visual de partículas basada en IA",
    "AI-driven vulnerability management": "Gestión de vulnerabilidades basada en IA",
    "AI-enabled process mining": "Minería de procesos con IA",
    "AI-enabled reconciliation": "Conciliación con IA",
    "AI-orchestrated product design": "Diseño de producto orquestado por IA",
    "AI-powered RFP and knowledge assistant": "Asistente de RFP y de conocimiento impulsado por IA",
    "AI-powered archive access and extraction": "Acceso y extracción documental impulsados por IA",
    "AI-powered risk management and regulatory compliance": "Gestión de riesgos y cumplimiento regulatorio impulsados por IA",
    "AI-supported budget allocation": "Asignación presupuestaria asistida por IA",
    "AI-supported regulatory examinations and inspections": "Exámenes e inspecciones regulatorias asistidos por IA",
    "Supplier assessment AI": "IA de evaluación de proveedores",
    # --- Fiscal ---
    "Accurate tax report generation": "Generación precisa de informes fiscales",
    "Automate tax filing processes, analyze financial data, and generate accurate tax reports": "Automatización de la presentación de impuestos, análisis de datos financieros y generación precisa de informes fiscales",
    "Evaluate tax laws and regulations and provide recommendations": "Evaluación de la normativa fiscal y emisión de recomendaciones",
    "Evaluate tax laws and regulations and provide recommendations for tax planning, compliance, and risk management": "Evaluación de la normativa fiscal y emisión de recomendaciones de planificación fiscal, cumplimiento y gestión de riesgos",
    "Predictive tax planning, compliance, and risk management": "Planificación fiscal, cumplimiento y gestión de riesgos predictivos",
    # --- Cierre contable y asientos ---
    "Automated closing checklists": "Listas de verificación de cierre automatizadas",
    "Consolidate accounting records under different standards and currencies": "Consolidación de registros contables bajo distintas normas y divisas",
    "Identify missing monthly accruals": "Identificación de provisiones mensuales omitidas",
    "Identify missing monthly accruals based on historic trends": "Identificación de provisiones mensuales omitidas a partir de tendencias históricas",
    "Identify unusual entries during close period": "Identificación de asientos inusuales durante el periodo de cierre",
    "Identify unusual entries recorded during the close period": "Identificación de asientos inusuales registrados durante el periodo de cierre",
    "Journal Entry Automation & Close Value prediction": "Automatización de asientos contables y predicción del valor de cierre",
    "Monitor potentially suspect or fraudulent journal entries in real time": "Monitorización en tiempo real de asientos potencialmente sospechosos o fraudulentos",
    "Proactive detection of fraudulent activities": "Detección proactiva de actividades fraudulentas",
    "Reconcile account balances at transaction level": "Conciliación de saldos contables a nivel de transacción",
    "Reconcile account balances at transaction level to invoices, purchase orders and bank statements": "Conciliación de saldos contables a nivel de transacción con facturas, pedidos de compra y extractos bancarios",
    # --- Reporting y cumplimiento ---
    "Automated financial statement preparation": "Preparación automatizada de estados financieros",
    "Automated regulatory compliance": "Cumplimiento regulatorio automatizado",
    "Consolidate written financial reports": "Consolidación de informes financieros redactados",
    "Consolidate written financial reports into one compliant report": "Consolidación de informes financieros en un único informe conforme a normativa",
    "Draft sections of 10Q / 10K generation": "Generación de borradores de secciones de 10Q / 10K",
    "Financial rules and regulations interpretations": "Interpretación de normas y regulación financiera",
    "Financial rules interpretations": "Interpretación de normas financieras",
    "Generate account variance analysis and intelligent explanations": "Generación de análisis de desviaciones de cuentas con explicaciones inteligentes",
    "Generate draft regulatory filings": "Generación de borradores de informes regulatorios",
    "Global policy tracking": "Seguimiento de políticas globales",
    "Monitor emerging regulations and evaluate current state compliance": "Monitorización de la regulación emergente y evaluación del cumplimiento actual",
    "Narrative MD&A draft generation": "Generación del borrador narrativo del MD&A",
    "Predictive compliance monitoring": "Monitorización predictiva del cumplimiento",
    "Summarizing legislative documents": "Resumen de documentos legislativos",
    # --- Datos, plataforma y acceso ---
    "Automate financial data across diverse sources": "Automatización de datos financieros de fuentes diversas",
    "Chat with Finance data": "Conversación con los datos de Finanzas",
    "Code assistant for digital transformation": "Asistente de código para la transformación digital",
    "Data access for all": "Acceso a datos para toda la organización",
    "Enterprise-wide data search and access": "Búsqueda y acceso a datos en toda la compañía",
    "Generate metadata documentation": "Generación de documentación de metadatos",
    "Guided adaptable workflows for master data record changes": "Flujos guiados y adaptables para cambios en datos maestros",
    "Identify inconsistencies in master data": "Identificación de inconsistencias en los datos maestros",
    "Identify inconsistencies in master data records": "Identificación de inconsistencias en los registros de datos maestros",
    "Insights for all": "Análisis accesibles para toda la organización",
    "Smarter intelligence": "Inteligencia más avanzada",
    "Synthetic data generation": "Generación de datos sintéticos",
    # --- Analitica y direccion ---
    "Executive financial health overview": "Visión ejecutiva de la salud financiera",
    "Generate executive level overview of company financial health": "Generación de una visión ejecutiva de la salud financiera de la compañía",
    "Identify past data patterns to predict and improve future financial performance": "Identificación de patrones históricos para predecir y mejorar el rendimiento financiero futuro",
    "Identify patterns to predict future financial performance": "Identificación de patrones para predecir el rendimiento financiero futuro",
    "Mgmt Reporting Actuals Plan Variance + Commentary": "Informes de gestión con real, plan, desviación y comentario",
    "Perform analysis and investigation and provide insights on demand": "Realización de análisis e investigación con conclusiones bajo demanda",
    "Project-level recommendations": "Recomendaciones a nivel de proyecto",
    "Summarize and score project proposals": "Resumen y puntuación de propuestas de proyecto",
    "Summarize and score project proposals across the organization": "Resumen y puntuación de propuestas de proyecto en toda la organización",
    # --- Inversion y mercado ---
    "Generate investing strategies": "Generación de estrategias de inversión",
    "Generate investing strategies from consolidated market conditions": "Generación de estrategias de inversión a partir de las condiciones de mercado consolidadas",
    "Generate investing strategies from consolidated market conditions, internal financial performance, and firm objectives": "Generación de estrategias de inversión a partir de las condiciones de mercado consolidadas, el rendimiento financiero interno y los objetivos de la firma",
    "Next-level market intelligence": "Inteligencia de mercado de nueva generación",
    "Predictive company valuation analyzing financial data": "Valoración predictiva de la compañía a partir del análisis de datos financieros",
    "Recommend, summarize, and detect risk from M&A cleanroom data": "Recomendación, resumen y detección de riesgos a partir de los datos del clean room de M&A",
    "Research-based report generation / KYC": "Generación de informes de investigación / KYC",
    # --- Tesoreria ---
    "Enhance cash flow analysis": "Mejora del análisis de flujo de caja",
    "Enhance cash flow analysis, minimizing liquidity risks": "Mejora del análisis de flujo de caja, minimizando riesgos de liquidez",
    "Enhance cash flow analysis, minimizing liquidity risks, improving forecasting accuracy, and maximizing returns on cash holdings": "Mejora del análisis de flujo de caja, minimizando riesgos de liquidez, mejorando la precisión de las previsiones y maximizando el rendimiento de la tesorería",
    "Intraday liquidity optimization": "Optimización de la liquidez intradía",
    "Optimize foreign exchange operations": "Optimización de las operaciones de divisa",
    "Optimize foreign exchange operations by evaluating foreign exchange data and identifying patterns and trends to reduce financial risks": "Optimización de las operaciones de divisa evaluando datos de tipo de cambio e identificando patrones y tendencias para reducir riesgos financieros",
    "Predictive cash flow forecasting tool": "Herramienta predictiva de previsión de flujo de caja",
    # --- Ciclo de cliente y de proveedor ---
    "Automated invoice error detection & correction": "Detección y corrección automatizada de errores en facturas",
    "Denial appeal letters": "Cartas de recurso ante denegaciones",
    "Drafting contracts and SoWs": "Redacción de contratos y SoW",
    "Facilitate payment collection to identify collections gaps and automate outreach": "Facilitación del cobro para identificar brechas de recobro y automatizar el contacto",
    "Generate customized invoices for nonstandard customer orders": "Generación de facturas personalizadas para pedidos de cliente no estándar",
    "Identify & proactively correct revenue leakage": "Identificación y corrección proactiva de fugas de ingresos",
    "Identify expense classification errors": "Identificación de errores de clasificación de gastos",
    "Predicts late payments or defaults": "Predicción de retrasos en el pago o impagos",
    "Read customer contracts and identify performance obligations": "Lectura de contratos de cliente e identificación de obligaciones de desempeño",
    "Recommend most optimal payment timing": "Recomendación del momento óptimo de pago",
    "Recommend optimal payment terms to improve DSO": "Recomendación de condiciones de pago óptimas para mejorar el DSO",
    "Using data from contract management system forecast monthly expense": "Previsión del gasto mensual con datos del sistema de gestión de contratos",
    "Using data from contract management system, forecast monthly expense for all third-party contracts": "Previsión del gasto mensual de todos los contratos con terceros con datos del sistema de gestión de contratos",
    # --- Comercial, cadena de suministro y operaciones ---
    "Autonomous drone-based infrastructure inspection": "Inspección autónoma de infraestructuras con drones",
    "Autonomous field operations management": "Gestión autónoma de operaciones de campo",
    "Autonomous supply chain operations": "Operaciones autónomas de cadena de suministro",
    "Autonomous warranty adjudication": "Resolución autónoma de garantías",
    "Capture variations and exceptions in P2P/O2C enabling touchless close": "Captura de variaciones y excepciones en P2P/O2C que habilita el cierre sin intervención",
    "Dynamic inventory management": "Gestión dinámica de inventario",
    "Dynamic pricing and inventory optimization": "Precios dinámicos y optimización de inventario",
    "End-to-end autonomous drug discovery and development": "Descubrimiento y desarrollo de fármacos autónomo de extremo a extremo",
    "Examine market trends, supplier behavior, and other factors to determine optimal prices": "Examen de tendencias de mercado, comportamiento de proveedores y otros factores para determinar precios óptimos",
    "Grid and energy efficiency optimization": "Optimización de la red y de la eficiencia energética",
    "Hyper-personalized sales and marketing assistant": "Asistente hiperpersonalizado de ventas y marketing",
    "Integrated business planning": "Planificación integrada de negocio",
    "Intelligent commercial operations": "Operaciones comerciales inteligentes",
    "Marketing content assistant": "Asistente de contenidos de marketing",
    "Next-generation store operations": "Operaciones de tienda de nueva generación",
    "On demand forecasting and scenario modeling": "Previsión y modelización de escenarios bajo demanda",
    "Planning for promotions": "Planificación de promociones",
    "Proactive defect resolution recommendations": "Recomendaciones proactivas para la resolución de incidencias",
    "Recommend demand planning, product costing, and pricing setting": "Recomendación de planificación de demanda, coste de producto y fijación de precios",
    "Resilient logistics and planning": "Logística y planificación resilientes",
    "Smarter clinical trials": "Ensayos clínicos más inteligentes",
    # --- Presupuesto ---
    "Develop guided workflows for creating budgets": "Desarrollo de flujos guiados para la elaboración de presupuestos",
    # --- Nombres de producto: se dejan como estan ---
    "Digital Analyst on demand analytics": "Analítica bajo demanda con Digital Analyst",
    "Digital analyst": "Digital analyst",
    "FinanceAI Insights Platform": "FinanceAI Insights Platform",
    "Predictive Analysis + GenAI": "Análisis predictivo + GenAI",
    # --- Variantes que en el original empiezan en minuscula ---
    # Se enumeran aparte en lugar de normalizar mayusculas al vuelo: el original
    # las escribe asi y el conversor guarda la cadena literal, de modo que
    # respetarlas es lo que mantiene el diff limitado a la traduccion.
    "anomaly detection during close": "detección de anomalías durante el cierre",
    "automate financial data across diverse sources": "automatización de datos financieros de fuentes diversas",
    "automated closing checklists": "listas de verificación de cierre automatizadas",
    "automated report consolidation": "consolidación automatizada de informes",
    "consolidate written financial reports into one compliant report": "consolidación de informes financieros en un único informe conforme a normativa",
    "draft sections of 10Q/10K": "borradores de secciones de 10Q/10K",
    "executive financial health overview": "visión ejecutiva de la salud financiera",
    "financial rules and regulations interpretations": "interpretación de normas y regulación financiera",
    "generate account variance analysis and intelligent explanations": "generación de análisis de desviaciones de cuentas con explicaciones inteligentes",
    "generate metadata documentation": "generación de documentación de metadatos",
    "guided workflows for master data record changes": "flujos guiados para cambios en datos maestros",
    "identify expense classification errors": "identificación de errores de clasificación de gastos",
    "identify inconsistencies in master data": "identificación de inconsistencias en los datos maestros",
    "identify inconsistencies in master data records": "identificación de inconsistencias en los registros de datos maestros",
    "identify unusual entries during close": "identificación de asientos inusuales durante el cierre",
    "monitor suspect journal entries in real time": "monitorización en tiempo real de asientos sospechosos",
    "proactive defect resolution recommendations": "recomendaciones proactivas para la resolución de incidencias",
    "project-level recommendations": "recomendaciones a nivel de proyecto",
    "suspect journal entry monitoring": "monitorización de asientos sospechosos",
    "touchless close": "cierre sin intervención",
    "Mgmt reporting actuals/plan/variance + commentary": "informes de gestión con real/plan/desviación y comentario",
}
